name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SERVER_IP: ${{ env.SERVER_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy code to server
        run: |
          echo $SSH_USER
          sshpass -p "$SSH_PASSWORD" ssh "$SSH_USER@$SERVER_IP" "cd /var/www/html/fuelfree.in && git pull origin main"
